# ---------------------------------------------------------------------------------------------
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com).
# All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------------------------------------------

-
  name: "Remove REST Delivery Point Configuration"
  hosts: all
  gather_facts: no
  any_errors_fatal: true
  module_defaults:
    solace_cert_authority:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
    solace_client_username:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_queue:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"
    solace_rdp:
      host: "{{ sempv2_host }}"
      port: "{{ sempv2_port }}"
      secure_connection: "{{ sempv2_is_secure_connection }}"
      username: "{{ sempv2_username }}"
      password: "{{ sempv2_password }}"
      timeout: "{{ sempv2_timeout }}"
      msg_vpn: "{{ vpn }}"

  tasks:

    # DEBUG
    # - meta: end_play

    - include_vars:
        file: "{{ SETTINGS_FILE }}"
        name: settings

    - include_vars:
        file: "./lib/vars.rdp.yml"
        name: rdp

    - name: "RDP: Remove"
      solace_rdp:
        name: "{{ rdp.name }}"
        state: absent

    - name: "Queue: Remove"
      solace_queue:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ rdp.queues }}"

    - name: "Client Username: Remove"
      solace_client_username:
        name: "{{ rdp.name }}"
        state: absent

    - name: "Certificate: Remove if TLS"
      solace_cert_authority:
        name: "{{ settings.az_cert_auth.name }}"
        state: absent
      when: settings.az_rdp_2_blob_func.az_func_tls_enabled == true



###
# The End.
