# ---------------------------------------------------------------------------------------------
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com).
# All rights reserved.
# Licensed under the MIT License.
# ---------------------------------------------------------------------------------------------

---
  az_rdp_2_blob_func:
    az_func_name: solace-rdp-2-blob
    az_func_code: "none"
    az_func_host: "host.docker.internal"
    az_func_port: 7071
    az_func_tls_enabled: false
    az_func_trusted_common_name: "*.domain.com"
    az_func_outgoing_connection_count: 1
    az_func_max_response_wait_time_secs: 60
    az_func_connection_retry_delay_secs: 5

###
# The End.
